Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-11, with the labels that each got.

#565 Store the totaltime when playback has ended
  resources/lib/playerinfo.py
Labels: enhancement

#563 Making settings instantaneous
  resources/lib/apihelper.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
Labels: enhancement

#566 Improve testing
  .travis.yml
  Makefile
  addon.xml
  resources/lib/addon_entry.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/service_entry.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/userdata/addon_settings.json
  test/userdata/global_settings.json
  test/xbmc.py
  test/xbmcvfs.py
Labels: testing

#569 Add new featured categories
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/search.py
  test/test_vrtplayer.py
Labels: enhancement

#572 Set Kodi watched status from VRT NU resumepoints
  resources/lib/metadata.py
Labels: enhancement

#575 Replace kodiwrapper with kodiutils
  resources/lib/addon.py
  resources/lib/addon_entry.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/test_apihelper.py
  test/test_favorites.py
  test/test_kodi.py
  test/test_resumepoints.py
  test/test_search.py
  test/test_streamservice.py
  test/test_tokenresolver.py
  test/test_tvguide.py
  test/test_vrtplayer.py
Labels: enhancement

#576 Backport test infrastructure and more tests
  resources/lib/apihelper.py
  resources/lib/playerinfo.py
  resources/lib/statichelper.py
  test/run.py
  test/test_apihelper.py
  test/test_kodiutils.py
  test/test_language.py
  test/test_proxy.py
  test/test_routing.py
  test/test_search.py
  test/test_settings.py
  test/test_statichelper.py
  test/test_tokenresolver.py
  test/test_vrtplayer.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
Labels: testing

#578 More testing
  resources/lib/apihelper.py
  resources/lib/kodiutils.py
  resources/lib/statichelper.py
  test/test_kodiutils.py
  test/test_resumepoints.py
  test/test_routing.py
  test/test_settings.py
  test/test_statichelper.py
  test/test_streamservice.py
  test/test_tokenresolver.py
  test/test_vrtplayer.py
  test/xbmc.py
Labels: testing

#580 Assorted fixes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiutils.py
  resources/lib/streamservice.py
  resources/settings.xml
  test/test_kodiutils.py
  test/test_resumepoints.py
  test/test_settings.py
  test/test_statichelper.py
  test/test_tokenresolver.py
Labels: bug, enhancement

#583 Use video_id for Up Next because whatson_id is not unique
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/service.py
  resources/lib/statichelper.py
  resources/lib/vrtplayer.py
  test/test_routing.py
  test/test_statichelper.py
  test/test_vrtplayer.py
Labels: bug

#584 Assorted fixes
  .codecov.yml
  .gitignore
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  test/xbmcaddon.py
Labels: bug, enhancement

#585 Use SPDX identifier for license
  addon.xml
Labels: release

#586 This fixes a known issue on Python 3.5
  resources/lib/service.py
Labels: bug

#587 Assorted fixes
  Makefile
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/metadata.py
  resources/lib/resumepoints.py
  resources/lib/service.py
  test/test_resumepoints.py
  test/test_routing.py
  tox.ini
Labels: enhancement

#588 Assorted fixes
  .codecov.yml
  Makefile
  resources/lib/apihelper.py
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/service.py
  test/xbmcgui.py
  tox.ini
Labels: bug, enhancement

#589 Replace hexlify with encode('hex')
  resources/lib/service.py
Labels: bug, enhancement

#593 Fix pylint useless suppressions
  Makefile
  resources/lib/kodiutils.py
  resources/lib/service.py
  resources/lib/tokenresolver.py
  test/test_apihelper.py
  test/test_favorites.py
  test/test_kodiutils.py
  test/test_language.py
  test/test_proxy.py
  test/test_resumepoints.py
  test/test_routing.py
  test/test_search.py
  test/test_settings.py
  test/test_statichelper.py
  test/test_streamservice.py
  test/test_tokenresolver.py
  test/test_tvguide.py
  test/test_vrtplayer.py
  test/xbmc.py
  test/xbmcvfs.py
Labels: testing

#594 Attempt to fix codecov madness
  .github/codecov.yml
  Makefile
Labels: testing

#595 Asynchronous resumepoint updates
  resources/lib/resumepoints.py
  resources/lib/service.py
Labels: enhancement

#597 Improve playerinfo
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/service.py
  resources/lib/vrtplayer.py
  test/xbmcgui.py
Labels: enhancement

#596 Leave notification_time up to Up Next
  Makefile
  resources/lib/apihelper.py
  resources/lib/kodiutils.py
Labels: enhancement

#599 Fix remaining issues
  Makefile
  resources/lib/apihelper.py
  resources/lib/playerinfo.py
Labels: bug

#602 Only process PlayerInfo events from VRT NU
  resources/lib/playerinfo.py
Labels: enhancement

#603 Backport small improvements
  Makefile
  resources/lib/kodiutils.py
Labels: enhancement

#606 Fix performance regression and add profiling framework
  .gitignore
  Makefile
  resources/lib/kodiutils.py
  test/read_profiling_stats.py
  test/xbmc.py
Labels: bug, testing

#608 Renew ADDON on every invocation
  resources/lib/addon.py
  resources/lib/addon_entry.py
  resources/lib/kodiutils.py
Labels: bug

#605 Assorted fixes
  resources/lib/apihelper.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/tokenresolver.py
  test/test_streamservice.py
Labels: enhancement
