Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-10, with the labels that each got.

#509 Filter based on max_log_level correctly
  resources/lib/kodiwrapper.py
Labels: bug

#512 Fixed proxy.py version for Python 2.7
  requirements.txt
Labels: testing

#515 Use programUrl instead of targetUrl
  resources/lib/apihelper.py
  resources/lib/metadata.py
Labels: enhancement

#514 Add availability and Geoblocked on the same line
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/metadata.py
Labels: enhancement

#516 Add categories as 'tag' in metadata
  resources/lib/metadata.py
Labels: enhancement

#506 Implement support for resumepoints
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/statichelper.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/test_apihelper.py
  test/test_favorites.py
  test/test_resumepoints.py
  test/test_search.py
  test/test_statichelper.py
  test/test_vrtplayer.py
  test/xbmc.py
Labels: enhancement

#518 Rename My favorites menu items
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/tokenresolver.py
  resources/settings.xml
  test/userdata/global_settings.json
  test/xbmc.py
Labels: bug, enhancement

#520 Various resumepoint fixes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/statichelper.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/test_resumepoints.py
  test/test_routing.py
  test/test_tokenresolver.py
  test/userdata/addon_settings.json
Labels: enhancement

#525 Improve TV guide with new metadata
  resources/lib/metadata.py
  test/xbmcplugin.py
Labels: enhancement

#526 Small fix
  resources/lib/metadata.py
Labels: bug

#530 Add playing-now information to livetv label
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/tvguide.py
Labels: enhancement

#531 Fix last hour for offline content
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/metadata.py
Labels: bug

#532 Add Python 3.8 testing and setuptools requirement
  .travis.yml
  requirements.txt
Labels: testing

#533 Also add now-playing to channel-centric listing
  resources/lib/apihelper.py
Labels: enhancement

#536 Assorted fixes
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
Labels: bug, enhancement

#537 Only instantiate KodiWrapper when needed
  resources/lib/service.py
Labels: enhancement

#538 Add HTTP error to dialog
  resources/lib/streamservice.py
  resources/lib/vrtplayer.py
Labels: enhancement

#540 Move addon settings into Addon stub
  test/test_favorites.py
  test/test_resumepoints.py
  test/test_streamservice.py
  test/xbmcaddon.py
  test/xbmcextra.py
Labels: testing

#550 Skip proxy test on Python 2
  test/test_proxy.py
  test/xbmcvfs.py
Labels: testing

#549 Fix Universiteit van Vlaanderen Up Next bug
  resources/lib/apihelper.py
  resources/lib/playerinfo.py
  resources/lib/vrtplayer.py
Labels: bug

#552 Implement Integration settings
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/settings.xml
Labels: enhancement

#553 Only refresh container if the play action was initiated from it
  resources/lib/kodiwrapper.py
  resources/lib/vrtplayer.py
Labels: enhancement

#558 Make sure we don't write empty tokens to cache
  resources/lib/tokenresolver.py
Labels: bug

#559 Fix a logic error
  resources/lib/kodiwrapper.py
Labels: bug

#562 Change the order of context menu items
  resources/lib/apihelper.py
  resources/lib/metadata.py
Labels: enhancement

#561 Use same margin for resumepoints and upnext
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/metadata.py
  resources/lib/resumepoints.py
Labels: enhancement
