Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-03, with the labels that each got.

#73 Visual improvements to menu listings
  plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
  plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#78 Handle HTML entities in data
  .travis.yml
  Makefile
  plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
Labels: bug

#80 Keep static order in main/live menu
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#81 Add more appropriate content to menu listing
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#82 Add fanart to menus
  plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
  plugin.video.vrt.nu/vrtnutests/streamservicetests.py
Labels: enhancement

#83 Fix typo
  plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
Labels: bug

#85 improved episode and season items
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
Labels: enhancement

#74 Prepare for release 1.7.0
  README.md
  plugin.video.vrt.nu/addon.xml
Labels: enhancement

#86 More visual improvements
  README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
  plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
  plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
  pylintrc
Labels: enhancement

#93 Add SOCKS detection to proxy support
  README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
  plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
Labels: enhancement

#97 Simplify the logic
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
Labels: enhancement

#98 Release v1.7.0
  README.md
  plugin.video.vrt.nu/addon.xml
Labels: enhancement

#90 Refactor package maker
  MakeZipWindows.bat
  packagemaker/Packagemaker.csproj
  packagemaker/Program.cs
  packagemaker/Properties/PublishProfiles/FolderProfile.pubxml
  plugin.video.vrt.nu.sln
  plugin.video.vrt.nu/plugin.video.vrt.nu.pyproj
  windowszipmaker/Packagemaker.deps.json
  windowszipmaker/Packagemaker.dll
  windowszipmaker/Packagemaker.pdb
  windowszipmaker/Packagemaker.runtimeconfig.json
Labels: enhancement

#99 kodi addon checker
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
Labels: enhancement

#110 Remove inputstream.adaptive requirement for Krypton
  README.md
  plugin.video.vrt.nu/addon.xml
Labels: bug

#111 Improve GitHub templates, add feature/question
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/propose-feature.md
Labels: enhancement

#114 Rename feature template
  .github/ISSUE_TEMPLATE/propose_feature.md
Labels: enhancement

#115 Improve thumbnail/fanart information
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
Labels: enhancement

#117 Make code more robust
  plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
  plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#102 Restructure project to make testing branches easier
  .gitignore
  .travis.yml
  Build-Zip.ps1
  MakeZipWindows.bat
  Makefile
  addon.py
  addon.xml
  packagemaker/Packagemaker.csproj
  packagemaker/Program.cs
  packagemaker/Properties/PublishProfiles/FolderProfile.pubxml
  plugin.video.vrt.nu.pyproj
  plugin.video.vrt.nu.sln
  resources/__init__.py
  resources/fanart.jpg
  resources/icon.png
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/__init__.py
  resources/lib/helperobjects/__init__.py
  resources/lib/helperobjects/apidata.py
  resources/lib/helperobjects/helperobjects.py
  resources/lib/helperobjects/streamurls.py
  resources/lib/kodiwrappers/__init__.py
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/kodiwrappers/sortmethod.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/metadatacollector.py
  resources/lib/vrtplayer/metadatacreator.py
  resources/lib/vrtplayer/statichelper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/media/canvas.png
  resources/media/een.png
  resources/media/ketnet.png
  resources/media/sporza.png
  resources/settings.xml
  service.py
  test/__init__.py
  test/apihelpertests.py
  test/streamservicetests.py
  test/vrtplayertests.py
  windowszipmaker/Packagemaker.deps.json
  windowszipmaker/Packagemaker.dll
  windowszipmaker/Packagemaker.pdb
  windowszipmaker/Packagemaker.runtimeconfig.json
Labels: enhancement, question

#108 Add screenshots
  addon.xml
  plugin.video.vrt.nu.pyproj
  resources/images/fanart.jpg
  resources/images/icon.png
  resources/images/screenshot01.jpg
  resources/images/screenshot02.jpg
  resources/images/screenshot03.jpg
Labels: enhancement

#119 fix virtual subclips in Kodi
  resources/lib/vrtplayer/streamservice.py
Labels: bug

#120 Better use resources/media/ only
  addon.xml
  plugin.video.vrt.nu.pyproj
  resources/media/fanart.jpg
  resources/media/icon.png
  resources/media/screenshot01.jpg
  resources/media/screenshot02.jpg
  resources/media/screenshot03.jpg
Labels: enhancement
