Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-08, with the labels that each got.

#408 fix broken streamservice webscraper
  resources/lib/streamservice.py
  test/test_routing.py
Labels: bug

#410 improve credentials handling
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/service.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/userdata/addon_settings.json
Labels: bug, enhancement

#412 Assorted changes
  .travis.yml
  Makefile
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/metadata.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  test/run.py
  test/xbmcextra.py
  test/xbmcplugin.py
Labels: enhancement

#415 exclude .pyo files from zip
  Makefile
Labels: enhancement

#416 New artwork
  addon.xml
  resources/lib/vrtplayer.py
  resources/media/fanart.jpg
  resources/media/fanart.png
  resources/media/icon.png
Labels: enhancement

#417 fix roaming
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
Labels: bug

#419 Use new high-res fanart by default
  Build-Zip.ps1
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/search.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/test_kodi.py
  test/test_routing.py
Labels: enhancement

#421 never set self._favorites to None
  resources/lib/favorites.py
Labels: bug

#425 added go to program context menu
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/metadata.py
Labels: enhancement

#428 Bring together all caching settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: enhancement

#430 fix my programs menu
  resources/lib/favorites.py
Labels: bug

#427 Fix features/categories ordering in en_gb
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/metadata.py
  resources/lib/tvguide.py
Labels: enhancement

#431 Remove the use of coloured icons as fanart
  addon.xml
  resources/lib/apihelper.py
  resources/lib/tvguide.py
Labels: enhancement

#433 support special chars in credentials
  resources/lib/kodiwrapper.py
  resources/lib/tokenresolver.py
Labels: bug

#432 Move tokens to userdata/tokens/
  .gitignore
  resources/lib/kodiwrapper.py
  resources/lib/tokenresolver.py
  resources/lib/vrtplayer.py
Labels: enhancement

#437 Add "Go to program" context to Favorites
  resources/lib/metadata.py
Labels: enhancement

#436 Add breadcrumbs support
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/search.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/xbmcplugin.py
Labels: enhancement

#434 Prepare for v2.2.0 release
  README.md
  addon.xml
Labels: release

#438 Ensure breadcrumbs always include 'VRT NU'
  resources/lib/kodiwrapper.py
Labels: enhancement

#443 use Kodi JSON-RPC API for delete_cached_thumbnail function
  resources/lib/kodiwrapper.py
  test/xbmc.py
Labels: enhancement

#444 unicode fix
  resources/lib/service.py
Labels: bug

#446 delete cache when upgrading to version 2.2.1
  resources/lib/vrtplayer.py
Labels: enhancement

#445 Prepare for v2.2.1 release
  README.md
  addon.xml
Labels: release

#448 Assorted changes
  .travis.yml
  README.md
  addon.xml
Labels: enhancement

#449 Go to 'allseasons'
  resources/lib/addon.py
  resources/lib/metadata.py
Labels: bug, enhancement

#452 Add InputStream Helper to Troubleshooting settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: enhancement

#456 Backport improvements from inputstreamhelper
  .gitignore
  test/test_streamservice.py
  test/userdata/addon_settings.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: enhancement

#454 Rename 'My programs' to 'My favorites'
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/vrtplayer.py
Labels: enhancement

#453 Add a screenshot to the README.md
  README.md
Labels: enhancement

#455 Remove Widevine installation (API and settings)
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/kodiwrapper.py
  resources/settings.xml
Labels: enhancement

#458 Add coverage support
  .coveragerc
  .travis.yml
  README.md
  requirements.txt
  test/test_favorites.py
  test/test_streamservice.py
Labels: enhancement

#461 Rename "No transmission" to "Retransmissions"
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement

#457 Prepare for v2.2.2
  .gitignore
  README.md
  addon.xml
Labels: release

#462 Update version
  addon.xml
Labels: release
