Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-07, with the labels that each got.

#335 Prepare for v2.0.0 release
  README.md
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement

#352 Add an action to check your credentials from the add-on settings.
  .gitignore
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/tokenresolver.py
  resources/settings.xml
Labels: enhancement

#355 Add a run command for CLI testing/debugging
  resources/lib/statichelper.py
  test/run.py
Labels: bug, enhancement

#356 Implement unittest conventions
  .travis.yml
  Makefile
  test/test_apihelper.py
  test/test_favorites.py
  test/test_routing.py
  test/test_search.py
  test/test_streamservice.py
  test/test_tvguide.py
  test/test_vrtplayer.py
Labels: enhancement

#360 Add Radio 1 live TV stream
  resources/lib/__init__.py
  test/test_apihelper.py
Labels: enhancement

#363 Add notifications to actions from settings
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/tokenresolver.py
  resources/settings.xml
Labels: enhancement

#357 Various visual improvements
  addon.xml
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  test/test_apihelper.py
  test/test_tvguide.py
  test/xbmc.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
Labels: enhancement

#364 Add YouTube support to VRT NU plugin
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/__init__.py
  resources/lib/kodiwrapper.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  resources/settings.xml
Labels: enhancement

#365 Fix incorrect translation ids
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: bug

#369 fix roaming when playertoken is expired
  resources/lib/tokenresolver.py
Labels: bug

#368 add method to play a program given a channel and airdate
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/test_routing.py
Labels: enhancement

#371 Set offscreen=True for ListItems
  addon.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/search.py
  resources/lib/vrtapihelper.py
  test/test_routing.py
  test/xbmcgui.py
Labels: bug, enhancement

#372 improve airdate function
  resources/lib/kodiwrapper.py
  resources/lib/streamservice.py
  resources/lib/vrtapihelper.py
  test/xbmc.py
Labels: enhancement

#374 Add banner information to episodes (basically fanart)
  resources/lib/vrtapihelper.py
Labels: enhancement

#370 Prepare for v2.1.0 release
  README.md
  addon.xml
Labels: release

#375 Rename Geo-locked to Geo-blocked
  resources/lib/metadatacreator.py
  resources/lib/vrtapihelper.py
Labels: enhancement

#376 Fix a few small sanity issues
  resources/lib/vrtapihelper.py
  tox.ini
Labels: enhancement

#377 Prepare for v2.1.0 release
  README.md
  addon.xml
Labels: release

#378 fix python3 bug when roaming
  resources/lib/tokenresolver.py
Labels: bug

#379 Handle a TypeError when download gets interrupted
  resources/lib/kodiwrapper.py
Labels: bug

#381 improved roaming handling
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/streamservice.py
Labels: bug, enhancement

#384 Integrate pyformat with localize()
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/search.py
  resources/lib/streamservice.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/test_kodi.py
Labels: enhancement

#386 Add TV show name to context menu
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/streamservice.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  test/test_search.py
Labels: enhancement

#390 Add search context menu and API calls
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/search.py
  resources/lib/vrtapihelper.py
  test/test_routing.py
Labels: enhancement

#387 Various code structure changes
  .travis.yml
  Build-Zip.ps1
  Makefile
  addon.xml
  requirements.txt
  resources/__init__.py
  resources/lib/__init__.py
  resources/lib/addon.py
  resources/lib/addon_plugin.py
  resources/lib/addon_service.py
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/metadatacreator.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/routing.py
  test/run.py
  test/test_apihelper.py
  test/test_favorites.py
  test/test_kodi.py
  test/test_routing.py
  test/test_search.py
  test/test_streamservice.py
  test/test_tvguide.py
  test/test_vrtplayer.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
Labels: bug, enhancement

#394 Browse TV Guide by channel first
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/data.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/test_routing.py
  test/test_tvguide.py
Labels: enhancement

#397 Backport fixes from v2.1.1
  addon.xml
  resources/lib/kodiwrapper.py
Labels: bug

#402 Small updates
  README.md
  addon.xml
  resources/lib/metadatacreator.py
Labels: enhancement

#395 reorganize apihelper/metadata for airdate/latestepisode support
  resources/lib/apihelper.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/metadatacreator.py
  resources/lib/search.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/test_apihelper.py
  test/test_favorites.py
  test/test_search.py
  test/test_vrtplayer.py
Labels: bug, enhancement

#406 fix extension point order
  addon.xml
Labels: bug, chorus, embruary
