Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-06, with the labels that each got.

#287 Fix translation and brands
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/metadatacreator.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
Labels: bug

#288 Add more docstrings
  README.md
  addon.xml
  requirements.txt
  resources/lib/__init__.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/metadatacreator.py
  resources/lib/router.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
Labels: enhancement

#291 move xbmcaddon to kodi wrapper
  resources/lib/kodiwrapper.py
  resources/lib/router.py
  service.py
  test/apihelpertests.py
  test/favoritestests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
  test/xbmcaddon.py
Labels: enhancement

#290 Add router unit tests
  .travis.yml
  Makefile
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
  resources/lib/streamservice.py
  resources/lib/vrtapihelper.py
  test/routertests.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
Labels: enhancement

#292 Remove Visual Studio files
  .gitignore
  plugin.video.vrt.nu.pyproj
  plugin.video.vrt.nu.sln
Labels: enhancement

#294 added function to play latest episode of a tv show
  resources/lib/__init__.py
  resources/lib/router.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
Labels: enhancement

#295 Fix translation strings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: bug

#296 Move global and addon settings to test/userdata
  .gitignore
  resources/lib/helperobjects.py
  resources/lib/vrtapihelper.py
  test/favoritestests.py
  test/streamservicetests.py
  test/userdata/addon_settings.json
  test/userdata/global_settings.json
  test/xbmc.py
  test/xbmcaddon.py
Labels: enhancement

#297 Add docstrings to remaining modules
  addon.xml
  pylintrc
  resources/lib/helperobjects.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/apihelpertests.py
  test/favoritestests.py
  test/routertests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
Labels: enhancement

#298 Add default values for missing settings
  resources/lib/kodiwrapper.py
  resources/lib/streamservice.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/xbmcaddon.py
Labels: enhancement

#309 fix empty streaming setting section when inputstream.adaptive is missing
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: enhancement

#317 Add a Refresh context menu
  resources/lib/__init__.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/router.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  service.py
  test/apihelpertests.py
  test/favoritestests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
Labels: enhancement

#316 Add a channel live tv entry in channel listing
  Makefile
  resources/lib/kodiwrapper.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/streamservicetests.py
  test/vrtplayertests.py
Labels: enhancement

#314 Clean url router
  resources/lib/__init__.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/router.py
  resources/lib/statichelper.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  service.py
  test/apihelpertests.py
  test/favoritestests.py
  test/routertests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
  test/xbmc.py
  test/xbmcplugin.py
Labels: enhancement

#318 Improve the router implementation using routing
  .travis.yml
  Makefile
  addon.py
  addon.xml
  pylintrc
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/__init__.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/router.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  service.py
  test/apihelpertests.py
  test/favoritestests.py
  test/routertests.py
  test/routing.py
  test/routingtests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
  test/xbmc.py
Labels: enhancement

#319 Add urls using routing
  addon.py
  pylintrc
  resources/lib/__init__.py
  resources/lib/kodiwrapper.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/apihelpertests.py
  test/favoritestests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
Labels: enhancement

#320 More cleanups to new routing interface
  addon.py
  resources/lib/streamservice.py
  resources/lib/vrtplayer.py
  test/routingtests.py
Labels: enhancement

#322 Add "Featured content" menu
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/__init__.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/routingtests.py
  test/vrtplayertests.py
Labels: enhancement

#324 Show movies and shortmovies directly
  resources/lib/__init__.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
Labels: enhancement

#325 Add My movies and My documentaries to My programs
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  resources/settings.xml
Labels: enhancement

#328 Assorted fixes
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/metadatacreator.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/apihelpertests.py
  test/routingtests.py
Labels: enhancement

#331 Fix issue with program titles including forward slash
  addon.py
  resources/lib/favorites.py
  resources/lib/vrtapihelper.py
  test/favoritestests.py
  test/routingtests.py
Labels: bug

#330 Improve Widevine/DRM settings text
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement

#333 Do not clear username if login failed
  resources/lib/helperobjects.py
Labels: enhancement

#334 Mix tvshows and oneoff episodes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/streamservice.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/vrtplayertests.py
Labels: enhancement

#337 Add favorites support to TV Guide
  resources/lib/statichelper.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  test/vrtplayertests.py
Labels: enhancement

#338 improve streaming settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/streamservice.py
  resources/lib/vrtapihelper.py
  resources/settings.xml
Labels: bug, enhancement

#340 localize favorites user interface
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
Labels: enhancement

#339 Only order 'unsorted' when tvshows + oneoff
  addon.xml
  resources/lib/kodiwrapper.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/apihelpertests.py
Labels: enhancement

#341 Add basic search menu and store search queries
  .gitignore
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/search.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  test/routingtests.py
  test/searchtests.py
Labels: enhancement

#342 Fix UTF8 issue with quote()
  resources/lib/tvguide.py
Labels: bug

#343 improve user interface strings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement

#345 Add a pop-up about the new v2.0.0 impact
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/vrtplayer.py
  resources/settings.xml
Labels: enhancement

#349 Assorted changes
  addon.py
  resources/lib/kodiwrapper.py
  resources/lib/metadatacreator.py
  resources/lib/vrtapihelper.py
  test/favoritestests.py
  test/routingtests.py
Labels: bug, enhancement

#350 fix quoted favorites
  addon.py
  resources/lib/vrtapihelper.py
Labels: bug

#353 Assorted changes
  resources/lib/kodiwrapper.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  test/routingtests.py
  test/xbmc.py
Labels: bug, enhancement
