Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-09, with the labels that each got.

#463 Simplify the availability of videos
  .gitignore
  .travis.yml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/metadata.py
Labels: enhancement

#464 Disable codecov-io github bot
  .coveragerc
  .github/codecov.yml
Labels: enhancement

#466 Improve breadcrumbs
  .github/codecov.yml
  .gitignore
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/data.py
  resources/lib/kodiwrapper.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/inputstreamhelper.py
  test/test_routing.py
Labels: enhancement

#467 Support credentials through environment
  test/test_favorites.py
  test/test_streamservice.py
  test/xbmcaddon.py
Labels: enhancement

#468 Try to fix the tests on Travis
  test/test_streamservice.py
Labels: enhancement

#469 Another attempt to fix commits in Travis
  resources/lib/statichelper.py
  test/userdata/global_settings.json
  test/xbmcplugin.py
Labels: enhancement

#470 Another attempt to fix Travis
  .travis.yml
  test/xbmcextra.py
Labels: enhancement

#471 Add missing routes and functionality
  test/test_routing.py
Labels: enhancement

#472 Improve coverage even more...
  test/test_routing.py
  test/userdata/search_history.json
Labels: enhancement

#473 Improve streamservice testing
  .pylintrc
  resources/lib/kodiwrapper.py
  resources/lib/streamservice.py
  test/test_streamservice.py
  test/userdata/search_history.json
  test/xbmcplugin.py
Labels: testing

#474 Some more testing tweaks
  .github/codecov.yml
  test/test_favorites.py
  test/test_streamservice.py
Labels: testing

#475 Simplify code for better coverage
  resources/lib/apihelper.py
  resources/lib/search.py
  resources/lib/statichelper.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
Labels: enhancement, testing

#476 Clean up codebase
  resources/lib/kodiwrapper.py
  resources/lib/statichelper.py
Labels: enhancement, testing

#478 Add proxy support to test framework
  test/xbmc.py
Labels: testing

#479 Another test using the proxy variables
  test/userdata/global_settings.json
  test/xbmc.py
Labels: testing

#481 More proxy tests for Travis
  resources/lib/kodiwrapper.py
  test/xbmc.py
Labels: testing

#480 Integrate new inputstreamhelper
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/kodiwrapper.py
  resources/settings.xml
  test/test_routing.py
  test/userdata/global_settings.json
  test/xbmc.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
Labels: enhancement

#482 Fix global settings and remove logging
  .github/codecov.yml
  resources/lib/kodiwrapper.py
  test/xbmc.py
Labels: testing

#483 Include tests that work for WORLD in Travis
  test/test_routing.py
Labels: testing

#484 Small updates
  .github/codecov.yml
  .pylintrc
  Makefile
  addon.xml
  resources/lib/apihelper.py
  resources/lib/kodiwrapper.py
  resources/lib/tokenresolver.py
  test/test_tvguide.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
Labels: enhancement, testing

#477 Move cursor down when ListItem is unfollowed/removed
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  test/routing.py
Labels: enhancement

#486 support user paths with unicode characters
  resources/lib/kodiwrapper.py
Labels: bug

#489 Make use of external Git requirements
  Makefile
  requirements.txt
  resources/lib/kodiwrapper.py
  test/inputstreamhelper.py
  test/routing.py
  test/xbmc.py
  test/xbmcgui.py
  test/xbmcplugin.py
Labels: testing

#490 Various fixes
  resources/language/resource.language.nl_nl/strings.po
  test/run.py
  test/userdata/addon_settings.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcvfs.py
Labels: bug, testing

#491 More various fixes
  test/test_favorites.py
  test/test_streamservice.py
Labels: bug, testing

#492 Fix pylint issues, backport xbmc framework
  .pylintrc
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  test/run.py
  test/test_apihelper.py
  test/test_favorites.py
  test/test_kodi.py
  test/test_routing.py
  test/test_search.py
  test/test_streamservice.py
  test/test_tvguide.py
  test/test_vrtplayer.py
  test/userdata/addon_settings.json
  test/userdata/global_settings.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
Labels: testing

#493 This fixes the credentials when testing
  test/xbmcextra.py
Labels: testing

#494 Small coverage fix
  .travis.yml
Labels: testing

#495 Add sanity checks for translations
  .travis.yml
  Makefile
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  test/test_favorites.py
  test/test_kodi.py
  test/test_streamservice.py
  test/userdata/global_settings.json
  test/xbmcaddon.py
  test/xbmcgui.py
Labels: bug, testing, translations

#496 Manage favorites through add-on settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/settings.xml
  test/test_routing.py
  test/userdata/addon_settings.json
  test/xbmcgui.py
  test/xbmcvfs.py
Labels: enhancement

#499 remove brace expansion from makefile
  Makefile
Labels: testing

#498 Improve testing using Travis credentials
  resources/lib/apihelper.py
  test/userdata/addon_settings.json
  test/userdata/search_history.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
Labels: testing

#501 A bunch of small fixes
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
  test/userdata/search_history.json
  test/xbmc.py
  test/xbmcgui.py
  test/xbmcplugin.py
Labels: enhancement

#502 Add banner art for information pane
  resources/lib/metadata.py
Labels: enhancement

#507 Various fixes
  .gitignore
  .pylintrc
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiwrapper.py
  resources/lib/metadata.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/test_statichelper.py
Labels: enhancement, testing

#497 Prepare for v2.2.3 release
  README.md
  addon.xml
  test/xbmcextra.py
Labels: release
