Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-05, with the labels that each got.

#161 Implement fallback for Categories web-scraping
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/metadatacreator.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/vrtplayertests.py
Labels: enhancement

#168 Fallback for live streams when web scraping fails
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#171 Add icon support
  addon.xml
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/media/canvas.png
  resources/media/een.png
  resources/media/ketnet.png
  resources/media/sporza.png
Labels: enhancement

#173 Improve module imports to speed up operation
  addon.py
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/metadatacreator.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/vrtplayertests.py
Labels: enhancement

#177 Add page-browsing to recent menu
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/vrtplayertests.py
Labels: enhancement

#178 Add channels menu
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#179 Add support for radio1 and klara
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/metadatacreator.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#180 Use different string ids to not corrupt Kodi
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
Labels: bug

#186 Prepare for v1.9.0 release
  README.md
  addon.xml
Labels: enhancement

#189 Implement inputstream.adaptive.max_bandwidth
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/settings.xml
Labels: enhancement

#182 allow Kodi to select lower bandwidth hls streams
  resources/lib/vrtplayer/streamservice.py
Labels: enhancement

#188 Enable 'reuselanguageinvoker'
  addon.xml
Labels: enhancement

#194 Test known brands
  resources/lib/vrtplayer/metadatacreator.py
  test/vrtplayertests.py
Labels: enhancement

#190 Reorganize settings
  README.md
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/actions.py
  resources/settings.xml
Labels: enhancement

#196 Improve bandwidth limitation settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/streamservice.py
  resources/settings.xml
Labels: enhancement

#199 Add new logging infrastructure
  addon.py
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
  test/vrtplayertests.py
Labels: enhancement

#200 Fix tvguide issue, add unit tests
  Makefile
  resources/lib/vrtplayer/tvguide.py
  test/tvguidetests.py
Labels: enhancement

#202 implemented max bandwidth for hls streams
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
Labels: enhancement

#203 Add 720p support without DRM
  resources/lib/vrtplayer/streamservice.py
Labels: enhancement

#204 Fix logging addon access
  addon.py
  resources/lib/kodiwrappers/kodiwrapper.py
Labels: bug

#205 Add "* All seasons" feature like stock Kodi
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#208 Add Ketnet Junior
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#211 Add setting to disabe menu caching
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/settings.xml
Labels: enhancement

#212 Fix caching
  pylintrc
  resources/lib/kodiwrappers/kodiwrapper.py
Labels: bug

#198 Fix unit tests
  .travis.yml
  Makefile
  addon.xml
  requirements.txt
  test/apihelpertests.py
  test/streamservicetests.py
  test/vrtplayertests.py
Labels: enhancement

#206 Add search functionality
  Makefile
  addon.py
  pylintrc
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/apihelpertests.py
  test/searchtests.py
Labels: enhancement

#215 Clean up object names
  addon.py
  resources/lib/helperobjects/helperobjects.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/apihelpertests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
Labels: enhancement

#216 Various small fixes
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#217 Various improvements to unit tests
  test/apihelpertests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
Labels: enhancement

#218 Clarify this is not endorsed by VRT
  README.md
  addon.xml
Labels: enhancement

#219 Assorted fixes
  Makefile
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
Labels: enhancement

#220 Fix categories scraper
  resources/lib/vrtplayer/vrtplayer.py
Labels: bug

#221 More assorted fixes
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  service.py
  test/__init__.py
  test/apihelpertests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
Labels: bug, enhancement

#222 Add season metadata
  resources/lib/vrtplayer/vrtapihelper.py
Labels: enhancement

#223 Ensure season and episode listings use correct view
  .travis.yml
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/apihelpertests.py
  test/searchtests.py
  test/vrtplayertests.py
Labels: enhancement

#224 Localize date format strings
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
Labels: bug

#226 Get credentials from credentials.json
  .gitignore
  test/__init__.py
  test/credentials.json
Labels: enhancement

#228 Fix a newly-introduced bug with long episode-lists
  .gitignore
  resources/lib/vrtplayer/vrtapihelper.py
  test/credentials.json
Labels: bug

#229 Support search highlights
  resources/lib/vrtplayer/statichelper.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: enhancement

#230 Clean up English translation
  resources/language/resource.language.en_gb/strings.po
  test/__init__.py
Labels: enhancement

#213 Add "My programs" menu
  Makefile
  addon.py
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/helperobjects/helperobjects.py
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/favorites.py
  resources/lib/vrtplayer/statichelper.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
  test/favoritestests.py
Labels: enhancement

#225 Make code more readable
  addon.py
  resources/lib/helperobjects/helperobjects.py
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/favorites.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  service.py
Labels: enhancement

#231 Re-add option to disable favorites
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/helperobjects/helperobjects.py
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/favorites.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
  service.py
  test/apihelpertests.py
  test/searchtests.py
  test/streamservicetests.py
  test/vrtplayertests.py
Labels: enhancement

#232 Various fixes
  .gitignore
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/actions.py
  resources/lib/vrtplayer/vrtapihelper.py
  test/__init__.py
  test/apihelpertests.py
  test/favoritestests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
Labels: enhancement

#233 Create permalinks for today, yesterday and tomorrow
  resources/lib/vrtplayer/tvguide.py
Labels: enhancement

#235 Fix spinner when not search term, or no results
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: bug

#234 Add TV-Guide information to live stream plot
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtplayer.py
  test/tvguidetests.py
Labels: bug, enhancement

#236 Various fixes and improvements
  Makefile
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/favorites.py
  resources/lib/vrtplayer/metadatacreator.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
Labels: bug, enhancement

#239 One more unicode fix
  resources/lib/vrtplayer/vrtapihelper.py
Labels: bug

#240 Assorted fixes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
Labels: bug, enhancement

#244 Fix Live TV EPG after midnight
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/tvguide.py
  test/apihelpertests.py
Labels: bug

#245 Fix TV guide for midnights
  resources/lib/vrtplayer/tvguide.py
Labels: bug

#246 Various fixes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/statichelper.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  test/tvguidetests.py
Labels: enhancement

#248 Disable setIsFolder use (Kodi 18 specific)
  resources/lib/kodiwrappers/kodiwrapper.py
Labels: bug

#251 Another batch of fixes
  addon.py
  resources/lib/vrtplayer/statichelper.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/apihelpertests.py
  test/searchtests.py
Labels: enhancement

#253 Add Soon offline menu
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/apihelpertests.py
Labels: enhancement

#254 Various small fixes
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/tvguide.py
  resources/settings.xml
Labels: enhancement

#256 Add 'Install Widevine' settings option
  README.md
  addon.py
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/favorites.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/settings.xml
  test/apihelpertests.py
Labels: enhancement

#257 Another batch of changes
  .travis.yml
  Makefile
  addon.xml
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/vrtplayer.py
  test/streamservicetests.py
Labels: enhancement

#259 Replace Mock with xbmc library replacement
  pylintrc
  resources/lib/kodiwrappers/kodiwrapper.py
  test/__init__.py
  test/apihelpertests.py
  test/favoritestests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
Labels: enhancement

#258 Implement caching framework
  addon.py
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/favorites.py
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
  test/vrtplayertests.py
  test/xbmcaddon.py
Labels: enhancement

#260 improve get_episodes
  resources/lib/__init__.pyo
  resources/lib/vrtplayer/streamservice.py
  resources/lib/vrtplayer/tokenresolver.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  test/apihelpertests.py
  test/vrtplayertests.py
Labels: bug

#261 Fix small last-minute issue
  resources/lib/kodiwrappers/kodiwrapper.py
Labels: bug

#262 Add option to enable/disable fanart
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer/tvguide.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/lib/vrtplayer/vrtplayer.py
  resources/settings.xml
Labels: enhancement

#265 Add a channel filter for Most recent and Soon offline
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrappers/kodiwrapper.py
  resources/lib/vrtplayer/vrtapihelper.py
  resources/settings.xml
  service.py
  test/xbmcaddon.py
Labels: enhancement

#267 Fix recalculation when using today, tomorrow, yesterday
  resources/lib/vrtplayer/tvguide.py
Labels: bug

#268 Add timing to 'No transmission'
  Makefile
  resources/lib/vrtplayer/tvguide.py
Labels: enhancement

#269 Restructure codebase
  Makefile
  addon.py
  pylintrc
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/__init__.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/helperobjects/__init__.py
  resources/lib/helperobjects/apidata.py
  resources/lib/helperobjects/helperobjects.py
  resources/lib/helperobjects/streamurls.py
  resources/lib/kodiwrapper.py
  resources/lib/kodiwrappers/__init__.py
  resources/lib/metadatacreator.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
  resources/lib/vrtplayer/__init__.py
  resources/lib/vrtplayer/metadatacreator.py
  service.py
  test/apihelpertests.py
  test/favoritestests.py
  test/searchtests.py
  test/streamservicetests.py
  test/tvguidetests.py
  test/vrtplayertests.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcgui.py
Labels: enhancement

#270 Prepare for v1.10.0 release
  addon.xml
Labels: enhancement

#271 Prepare for v1.10.0, the sequel
  addon.xml
Labels: enhancement

#272 Assorted set of fixes
  addon.py
  addon.xml
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
Labels: enhancement

#275 Fix invalidate caches, add docstrings
  resources/lib/__init__.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/metadatacreator.py
  resources/lib/statichelper.py
  resources/lib/vrtapihelper.py
  resources/lib/vrtplayer.py
Labels: bug, enhancement

#276 Fix channels/favorites
  addon.py
Labels: bug

#278 fix crash when xvrttoken is None
  resources/lib/favorites.py
Labels: bug

#282 Update add-on information
  README.md
  addon.xml
Labels: enhancement

#283 fix typos
  README.md
  addon.xml
Labels: enhancement

#284 Fix the GPL link in the badge
  README.md
Labels: enhancement

#285 Prepare for v1.10.0 release
  README.md
  addon.xml
Labels: enhancement

#286 Invalidate favorites cache when settings change
  README.md
  addon.py
  resources/lib/favorites.py
  resources/lib/kodiwrapper.py
  resources/lib/router.py
  resources/lib/statichelper.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/vrtapihelper.py
Labels: bug
