Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2019-12, with the labels that each got.

#611 Configurable number items per page
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/search.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/userdata/addon_settings.json
Labels: enhancement

#612 Make HTTP cache ttl configurable
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/search.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  resources/settings.xml
  test/userdata/addon_settings.json
Labels: enhancement

#613 More PlayerInfo improvements
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
  resources/lib/service.py
Labels: enhancement

#615 Support empty whatsonIds
  resources/lib/playerinfo.py
Labels: bug

#614 Assorted fixes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: enhancement

#610 Seamlessly play Up Next episodes
  resources/lib/apihelper.py
  resources/lib/playerinfo.py
  resources/lib/service.py
  test/xbmc.py
Labels: bug

#591 Support base64 payload for Up Next communication
  resources/lib/playerinfo.py
  resources/lib/service.py
Labels: enhancement

#618 Update 'Watch later' after watching episode
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
Labels: bug

#623 Make exceptions Python 2/3 compatible
  resources/lib/kodiutils.py
Labels: bug

#624 Attempt to use json.load(fd) again
  resources/lib/addon.py
  resources/lib/addon_entry.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/utils.py
  resources/lib/vrtplayer.py
  test/test_utils.py
  test/xbmc.py
Labels: bug, enhancement

#625 Use get_url_json for updating favorites and resumepoints
  resources/lib/favorites.py
  resources/lib/resumepoints.py
  resources/lib/streamservice.py
Labels: bug, enhancement

#627 Rename internal representation _data
  resources/lib/favorites.py
  resources/lib/resumepoints.py
  test/test_resumepoints.py
Labels: enhancement

#634 Improve integration tests
  test/test_apihelper.py
  test/test_favorites.py
  test/test_search.py
  test/test_vrtplayer.py
  test/userdata/addon_settings.json
Labels: testing

#631 Only push 'Up Next' when Kodi Player is playing
  resources/lib/playerinfo.py
Labels: enhancement

#635 Catch and report JSON TypeErrors
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/tokenresolver.py
  resources/lib/utils.py
  test/test_kodiutils.py
  test/test_resumepoints.py
Labels: bug

#637 Fix missing ListItem fanart
  resources/lib/kodiutils.py
Labels: bug

#636 Reduce manual container updates to absolute minimum
  resources/lib/playerinfo.py
  test/test_resumepoints.py
Labels: bug

#638 Close settings when installing an add-on
  resources/settings.xml
Labels: enhancement

#633 Extend jsonrpc() to support list of commands
  resources/lib/kodiutils.py
  test/test_kodiutils.py
  test/xbmc.py
Labels: enhancement

#639 Improve caching algorithm
  .gitignore
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/resumepoints.py
Labels: enhancement

#641 Get advanced settings as an integer
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
Labels: bug

#640 Remove entries from resume_points
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
Labels: enhancement

#645 Don't update total to 0.0
  resources/lib/playerinfo.py
Labels: bug

#647 Assorted fixed
  .gitignore
  .pylintrc
  Makefile
  resources/lib/addon.py
  resources/lib/addon_entry.py
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/favorites.py
  resources/lib/helperobjects.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/service.py
  resources/lib/service_entry.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/utils.py
  resources/lib/vrtplayer.py
  test/read_profiling_stats.py
  test/run.py
  test/test_apihelper.py
  test/test_favorites.py
  test/test_kodiutils.py
  test/test_language.py
  test/test_proxy.py
  test/test_resumepoints.py
  test/test_routing.py
  test/test_search.py
  test/test_settings.py
  test/test_streamservice.py
  test/test_tokenresolver.py
  test/test_tvguide.py
  test/test_utils.py
  test/test_vrtplayer.py
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
  tox.ini
Labels: testing

#650 Assorted resumepoint fixes
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  test/test_resumepoints.py
  test/test_routing.py
Labels: bug, enhancement

#654 Kodi 17 fixes
  resources/lib/playerinfo.py
Labels: bug

#656 Update screenshots
  resources/media/screenshot01.jpg
  resources/media/screenshot02.jpg
  resources/media/screenshot03.jpg
  resources/media/screenshot04.jpg
Labels: enhancement

#547 Prepare for v2.3.0 release
  README.md
  addon.xml
Labels: release

#658 Only listen to vrt nu add-on urls
  resources/lib/playerinfo.py
Labels: bug
