Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-03, with the labels that each got.

#689 Fix unit test
  test/test_vrtplayer.py
Labels: testing

#685 Add Radio 2 and events live stream
  .codecov.yml
  requirements.txt
  resources/lib/data.py
Labels: enhancement

#697 Initialize last_update as float
  test/userdata/addon_settings.json
Labels: bug

#511 Add colour preferences to accommodate light skins
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/tvguide.py
  resources/lib/utils.py
  resources/settings.xml
  test/userdata/addon_settings.json
Labels: enhancement

#699 Add a favourites music subsection
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/vrtplayer.py
  resources/settings.xml
Labels: enhancement

#698 Make oneoffs more strict
  resources/lib/apihelper.py
Labels: bug, enhancement, vrtnu

#700 Fix broken colors
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/search.py
  resources/lib/vrtplayer.py
Labels: bug

#701 Spelling fixes
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/helperobjects.py
  resources/lib/service.py
  resources/lib/streamservice.py
Labels: translations

#702 Use GitHub actions for CI testing
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  Makefile
  README.md
  codecov.yml
  requirements.txt
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/kodiutils.py
  resources/lib/resumepoints.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  tests/__init__.py
  tests/read_profiling_stats.py
  tests/run.py
  tests/test_apihelper.py
  tests/test_favorites.py
  tests/test_kodiutils.py
  tests/test_language.py
  tests/test_proxy.py
  tests/test_resumepoints.py
  tests/test_routing.py
  tests/test_search.py
  tests/test_settings.py
  tests/test_streamservice.py
  tests/test_tokenresolver.py
  tests/test_tvguide.py
  tests/test_utils.py
  tests/test_vrtplayer.py
  tests/test_webscraper.py
  tests/userdata/addon_settings.json
  tests/userdata/global_settings.json
  tests/userdata/search_history.json
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcextra.py
  tests/xbmcgui.py
  tests/xbmcplugin.py
  tests/xbmcvfs.py
  tox.ini
Labels: testing

#704 Update location after repo transfer
  README.md
  addon.xml
Labels: documentation

#703 Small fixes to GitHub CI workflow
  .github/workflows/ci.yml
  requirements.txt
Labels: testing

#705 Remove certain files from ZIP download
  .gitattributes
Labels: release

#706 Perform kodd-addon-checker from GitHub CI
  .github/workflows/addon-check.yml
  addon.xml
Labels: testing

#707 Add SonarCloud integration to GitHub CI
  .github/workflows/ci.yml
Labels: testing

#708 Allow coverage steps to fail
  .github/workflows/ci.yml
Labels: testing

#709 Small fix to sonar properties file
  .github/workflows/ci.yml
Labels: testing

#710 Sonarcloud final attempt
  .github/workflows/ci.yml
Labels: testing

#711 Improve coverage slightly
  .github/workflows/ci.yml
  Makefile
  resources/lib/resumepoints.py
  resources/lib/utils.py
  resources/lib/vrtplayer.py
  tests/test_favorites.py
  tests/test_resumepoints.py
  tests/test_routing.py
  tests/test_settings.py
  tests/test_streamservice.py
  tests/test_utils.py
  tests/userdata/addon_settings.json
Labels: testing

#714 Add credentials to service testing
  .github/workflows/ci.yml
Labels: testing

#713 Use SonarCloud action and Kodi addon-checker fixes
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
Labels: testing

#712 Refresh menu if the stream is not found
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/streamservice.py
  tests/test_streamservice.py
Labels: enhancement

#715 Remove codecov.yml and use Team Yaml
  .gitattributes
  codecov.yml
Labels: testing

#716 Add status workflow for VRT NU
  .github/workflows/status.yml
Labels: testing

#717 Fixes to status workflow
  .github/workflows/ci.yml
  .github/workflows/status.yml
Labels: testing

#718 Run status also on PR and push
  .github/workflows/status.yml
Labels: testing
