Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-09, with the labels that each got.

#811 Clean up workflows
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
Labels: enhancement, testing

#814 Get categories from online json
  .github/workflows/status.yml
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/webscraper.py
  tests/test_apihelper.py
  tests/test_vrtplayer.py
  tests/test_webscraper.py
Labels: enhancement

#797 Fix unwanted virtual subclip behaviour
  resources/lib/playerinfo.py
  resources/lib/streamservice.py
  tests/test_streamservice.py
Labels: bug

#817 Add product placement and kijkwijzer metadata
  resources/lib/metadata.py
  resources/lib/webscraper.py
Labels: enhancement

#818 Improve coverage
  addon.xml
  resources/lib/apihelper.py
  tests/test_routing.py
Labels: testing
