Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-04, with the labels that each got.

#722 Fix roaming
  resources/lib/tokenresolver.py
Labels: bug

#723 Add better add-on tests
  .gitattributes
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  .github/workflows/status.yml
  Makefile
  resources/lib/resumepoints.py
  tests/test_settings.py
  tests/test_tvguide.py
Labels: testing

#720 Ensure codebase is compatible with Kodi 19
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
  resources/lib/streamservice.py
  resources/lib/vrtplayer.py
  tests/xbmcgui.py
Labels: enhancement

#724 Fix a few more old booleans
  tests/test_streamservice.py
Labels: testing

#726 Handle HTTP 431 (Request header fields too large)
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiutils.py
Labels: bug

#730 Reinstate original vualto_radio1
  resources/lib/data.py
Labels: bug

#732 Fix new pylint check
  tests/xbmcgui.py
Labels: testing

#731 Support new inputstream Python api in Kodi 19
  resources/lib/kodiutils.py
Labels: enhancement

#729 Add basic M3U8 playlist file
  channels.m3u8
Labels: enhancement

#733 Automate release
  .github/workflows/release.yml
  Makefile
Labels: release

#736 Always select HLS-stream for vualto_radio1
  resources/lib/kodiutils.py
  resources/lib/streamservice.py
Labels: bug

#734 v2.3.3 release
  README.md
  addon.xml
  resources/media/screenshot01.jpg
  resources/media/screenshot02.jpg
  resources/media/screenshot03.jpg
  resources/media/screenshot04.jpg
Labels: release
