Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-01, with the labels that each got.

#659 Prepare 2.3.0 release again
  README.md
  addon.xml
  test/test_apihelper.py
  test/test_search.py
Labels: release

#660 Fix integration test
  test/test_streamservice.py
Labels: testing

#663 Fix undefined cache_file
  resources/lib/apihelper.py
Labels: bug

#665 Support multiple YouTube links per channel
  addon.xml
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/utils.py
Labels: enhancement

#666 Fallback to web scraping for watching activity
  resources/lib/apihelper.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/streamservice.py
  resources/lib/tvguide.py
  resources/lib/utils.py
  resources/lib/webscraper.py
  test/test_streamservice.py
  test/test_vrtplayer.py
  test/test_webscraper.py
Labels: bug, enhancement

#669 Fix livestreams
  resources/lib/data.py
  resources/lib/webscraper.py
  test/test_webscraper.py
Labels: bug, vrtnu

#668 Differentiate between Label and Title
  resources/lib/apihelper.py
  resources/lib/helperobjects.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/search.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  test/test_apihelper.py
  test/test_tvguide.py
  test/test_vrtplayer.py
Labels: enhancement

#672 Add support for Addon setting types
  .pylintrc
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/streamservice.py
  resources/lib/vrtplayer.py
  resources/lib/webscraper.py
  test/xbmcaddon.py
Labels: bug, enhancement

#673 Assorted metadata fixes
  resources/lib/metadata.py
Labels: enhancement

#676 Always preserve Up Next resumepoints
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
Labels: bug

#675 Prepare for v2.3.1 release
  README.md
  addon.xml
Labels: release

#677 Fix web scraping categories
  resources/lib/webscraper.py
Labels: bug

#678 Check if categories contain all necessary info
  resources/lib/webscraper.py
  test/test_webscraper.py
Labels: bug

#680 Assorted fixes
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/metadata.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/search.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/utils.py
  test/test_utils.py
  test/xbmcextra.py
Labels: bug, enhancement

#679 Prepare for v2.3.2 release
  README.md
  addon.xml
Labels: release

#684 Add Klara livestream
  requirements.txt
  resources/lib/data.py
Labels: enhancement
