Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-07, with the labels that each got.

#791 Return to directory listing when stream is None
  resources/lib/vrtplayer.py
Labels: bug

#790 Show error messages when connections fail
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/favorites.py
  resources/lib/kodiutils.py
  resources/lib/resumepoints.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
  resources/lib/tvguide.py
  resources/lib/webscraper.py
Labels: enhancement

#793 Prepare for v2.4.0 release
  README.md
  addon.xml
  resources/media/screenshot01.jpg
  resources/media/screenshot02.jpg
  resources/media/screenshot03.jpg
  resources/media/screenshot04.jpg
Labels: release

#794 Fix stop timestamp in virtual subclip
  resources/lib/streamservice.py
  tests/test_streamservice.py
Labels: bug

#798 Improve Up Next
  resources/lib/apihelper.py
Labels: bug

#799 Fix test using Postbus X
  tests/test_apihelper.py
Labels: testing

#796 Extend soon offline menu to seven days
  resources/lib/apihelper.py
  resources/lib/vrtplayer.py
Labels: enhancement

#801 Fix apihelper test for episodes without broadcastDate
  tests/test_apihelper.py
Labels: testing
