Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-05, with the labels that each got.

#738 Use GH_USERNAME secret for automatic submission
  .github/workflows/release.yml
Labels: bug

#739 Assorted fixes
  .github/workflows/addon-check.yml
  .pylintrc
  Makefile
  resources/lib/apihelper.py
  resources/lib/metadata.py
  resources/lib/utils.py
  tests/test_utils.py
Labels: enhancement

#740 Add query string to URI in log_access
  resources/lib/addon.py
  resources/lib/kodiutils.py
Labels: enhancement

#737 Add support for IPTV Manager
  channels.m3u8
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/data.py
  resources/lib/iptvmanager.py
  resources/lib/tvguide.py
  resources/settings.xml
Labels: enhancement

#742 Fix an Ubuntu issue with the add-on check
  .github/workflows/addon-check.yml
Labels: enhancement

#743 Add epg_id
  resources/lib/data.py
  resources/lib/iptvmanager.py
  resources/lib/tvguide.py
Labels: enhancement

#744 Always unescape html in subtitle and shortDescription
  resources/lib/metadata.py
  resources/lib/utils.py
Labels: bug

#747 Run all tests always (don't stop on failure)
  .github/workflows/ci.yml
  .github/workflows/status.yml
Labels: testing

#745 Assorted fixes
  .pylintrc
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiutils.py
  tests/test_kodiutils.py
  tests/test_resumepoints.py
  tests/test_routing.py
  tests/xbmcgui.py
  tests/xbmcplugin.py
Labels: bug, enhancement, testing, translations

#749 Add all screenshots
  README.md
Labels: documentation

#750 Fix user_xvrttoken
  resources/lib/tokenresolver.py
Labels: bug

#752 Mark IPTV Manager support as experimental
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
Labels: translations

#753 Prepare for v2.3.4 release
  README.md
  addon.xml
Labels: release

#757 Small backports from work on other add-ons
  resources/lib/utils.py
  tests/xbmc.py
  tests/xbmcgui.py
  tests/xbmcvfs.py
Labels: enhancement, testing

#756 Revert vualto_radio1 workaround
  resources/lib/streamservice.py
Labels: enhancement

#754 Rework tokenresolver
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/favorites.py
  resources/lib/resumepoints.py
  resources/lib/streamservice.py
  resources/lib/tokenresolver.py
Labels: bug, enhancement

#758 Abort when getting a roaming xvrttoken is going to fail
  resources/lib/tokenresolver.py
Labels: bug

#759 Log resumepoints as float
  resources/lib/metadata.py
Labels: bug

#760 Add support for playing from the Guide with IPTV Manager
  resources/lib/iptvmanager.py
Labels: enhancement

#761 This fixes an error on missing XSRF-TOKEN cookie
  resources/lib/tokenresolver.py
Labels: bug

#762 Fix XSRF token
  resources/lib/tokenresolver.py
Labels: bug

#763 Prepare for v2.3.5 release
  README.md
  addon.xml
  resources/settings.xml
Labels: release

#768 Python3 compability fix
  resources/lib/tvguide.py
Labels: bug

#767 Add a simple option for users to update VRT NU add-on
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/kodiutils.py
  resources/settings.xml
Labels: enhancement

#769 Add VRT NU app updates to status checks
  .github/workflows/status.yml
  tests/checkvrtnu.py
Labels: enhancement

#771 Make noop calls unique
  resources/lib/tvguide.py
Labels: enhancement
