Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-08, with the labels that each got.

#803 Fix HD-quality for virtual subclip HLS streams
  resources/lib/streamservice.py
Labels: bug

#805 Fix tests
  .pylintrc
  tests/test_apihelper.py
Labels: testing

#804 Fix Google Play Store check
  tests/checkvrtnu.py
Labels: testing

#806 Fix exception on SSLError/log_error
  resources/lib/kodiutils.py
Labels: bug

#807 Fix a known exception in TokenResolver
  resources/lib/tokenresolver.py
Labels: bug

#808 Increase time window for VRT NU version detection
  tests/checkvrtnu.py
Labels: bug, testing

#809 Handle none-responses from open_url
  resources/lib/tokenresolver.py
  resources/lib/webscraper.py
Labels: bug
