Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-12, with the labels that each got.

#834 Fix Categories
  resources/lib/data.py
  tests/test_apihelper.py
  tests/test_utils.py
Labels: bug, testing

#832 Fix invalid setting type
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/kodiutils.py
  resources/settings.xml
Labels: bug

#837 Fixes a date parsing issue on windows and run CI
  .github/workflows/ci.yml
  resources/lib/kodiutils.py
Labels: testing

#836 Support programs with more than 10 seasons
  resources/lib/apihelper.py
Labels: bug

#839 Remove '.html' from short programUrl
  resources/lib/utils.py
Labels: bug, vrtnu

#841 Fix seasons menu in Kodi 19
  resources/lib/apihelper.py
  resources/lib/metadata.py
Labels: bug

#840 Prepare for v2.4.2 release
  README.md
  addon.xml
Labels: release

#842 Don't log credentials in the Kodi debug log
  resources/lib/kodiutils.py
Labels: bug
