Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2020-06, with the labels that each got.

#770 Warn if automatic updates is disabled in Kodi
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/settings.xml
Labels: enhancement

#773 Use requests for HTTP communication
  tests/checkvrtnu.py
Labels: testing

#775 Fix VRT NU app release check
  tests/checkvrtnu.py
Labels: bug

#776 IPTV Manager improvements
  resources/lib/iptvmanager.py
  resources/lib/tvguide.py
Labels: enhancement

#778 Fix categories
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/apihelper.py
  resources/lib/data.py
  resources/lib/webscraper.py
  tests/test_vrtplayer.py
Labels: bug

#774 Integrate token cache in kodiutils
  resources/lib/kodiutils.py
  resources/lib/tokenresolver.py
Labels: enhancement

#779 Fix data transfers over 1 MB to IPTV Manager
  resources/lib/iptvmanager.py
Labels: bug

#777 Improve airdate api
  resources/lib/apihelper.py
  resources/lib/iptvmanager.py
Labels: enhancement

#780 Escape html in subtitle
  resources/lib/tvguide.py
Labels: bug

#782 Fix app release check
  tests/checkvrtnu.py
Labels: bug

#781 Improve playing from TV guide
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/metadata.py
  resources/lib/tvguide.py
  resources/lib/vrtplayer.py
  tests/test_routing.py
Labels: enhancement

#785 Fix season items
  resources/lib/apihelper.py
  tests/test_apihelper.py
  tests/test_vrtplayer.py
Labels: bug

#786 Fix testing random tvshow
  tests/test_vrtplayer.py
Labels: bug

#787 Add asserts to stubs
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcplugin.py
  tests/xbmcvfs.py
Labels: testing

#789 Fix getting cache paths
  resources/lib/kodiutils.py
Labels: bug
