Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2021-02, with the labels that each got.

#856 Fix livestream cache
  resources/lib/streamservice.py
Labels: bug

#855 Inform user that no time shift is possible without ISA
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/vrtplayer.py
Labels: documentation, enhancement, good first issue

#858 Prepare for v2.4.5 release
  README.md
  addon.xml
Labels: release
