Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2021-01, with the labels that each got.

#843 Fix tests
  tests/test_vrtplayer.py
Labels: testing

#845 Various backports
  Makefile
  README.md
  requirements.txt
  resources/lib/iptvmanager.py
  resources/lib/kodiutils.py
  tests/test_vrtplayer.py
  tests/xbmcaddon.py
  tests/xbmcextra.py
  tests/xbmcgui.py
  tests/xbmcplugin.py
  tests/xbmcvfs.py
Labels: enhancement, testing

#847 Use InputStream Adaptive to play HLS
  resources/lib/kodiutils.py
  resources/lib/playerinfo.py
  resources/lib/streamservice.py
Labels: enhancement

#772 Add livestream cache
  resources/lib/kodiutils.py
  resources/lib/streamservice.py
Labels: enhancement

#849 Add new Podium 19 channel
  resources/lib/data.py
  tests/test_apihelper.py
Labels: enhancement, testing

#850 Prepare for v2.3.4 release
  README.md
  addon.xml
Labels: release

#851 Fix version
  addon.xml
Labels: release

#852 Disable livestream cache when roaming
  resources/lib/streamservice.py
Labels: bug

#853 Prepare for v2.4.4 release
  README.md
  addon.xml
Labels: release

#857 Make use of git archive
  Makefile
Labels: testing
