Repository add-ons/plugin.video.vrt.nu, pull requests merged in 2022-10, with the labels that each got.

#1049 Fix go to program
  resources/lib/addon.py
  resources/lib/apihelper.py
  resources/lib/vrtplayer.py
  tests/test_apihelper.py
  tests/test_routing.py
  tests/test_vrtplayer.py
Labels: bug

#1052 Fix categories menu
  resources/lib/addon.py
  resources/lib/api.py
  resources/lib/vrtplayer.py
Labels: bug

#1054 Fix context menu
  resources/lib/api.py
  resources/lib/vrtplayer.py
Labels: bug

#1055 Fix featured menu
  resources/lib/api.py
  resources/lib/apihelper.py
  resources/lib/vrtplayer.py
Labels: bug

#1058 Fix soon offline menu
  resources/lib/addon.py
  resources/lib/api.py
  resources/lib/vrtplayer.py
Labels: bug

#1059 Fix paging in featured menu
  resources/lib/addon.py
  resources/lib/api.py
  resources/lib/vrtplayer.py
Labels: bug

#1060 Prepare for v2.5.18 release
  README.md
  addon.xml
Labels: release

#1062 Fix program menus
  resources/lib/api.py
Labels: bug

#1063 Fix Up Next and Resumepoints
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/api.py
  resources/lib/graphql_data.py
  resources/lib/playerinfo.py
  resources/lib/resumepoints.py
  resources/lib/vrtplayer.py
Labels: bug

#1066 Fix channels menu
  resources/lib/api.py
Labels: bug

#1065 Restore /play/url/ entrypoint
  resources/lib/addon.py
  resources/lib/streamservice.py
Labels: bug

#1067 Improve setting resumepoints when using Up Next
  resources/lib/api.py
  resources/lib/playerinfo.py
Labels: bug

#1068 Prepare for v2.5.19 release
  README.md
  addon.xml
Labels: release

#1069 Support Python 3.10
  .github/workflows/ci.yml
  resources/lib/api.py
  resources/lib/apihelper.py
  tests/checkvrtmax.py
Labels: testing

#1070 Fix getting art from api
  resources/lib/api.py
Labels: bug
